spring:
  application:
    name: ai-service
  config:
    import:
      - nacos:${spring.application.name}.yml
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8858}
        namespace: ${NACOS_NAMESPACE:}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        register-enabled: true
      config:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8858}
        namespace: ${NACOS_NAMESPACE:}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        file-extension: yml
        refresh-enabled: true
        fail-fast: true
